### ISSUE TITLE
Limit query results by pagination' limits

### ISSUE THREAD

**Issue by matteomoretti** [Abhoryo/APYDataGridBundle#686]
Hi,

I've a Source entity which results in a PHP grid of many rows (more than 8k). I use pagination and the grid displays correctly. 

However the sql query returns more than 8k rows and so it's extremely slow. 

How can I effectevely extract only the paginated and hence displayed rows? 
If I set a 50 paginated results, I should extract from db only 50 results instead of 8k.

Thanks a lot 

Kind  regards

Matteo

**Comment by Abhoryo** [comment]
I think that it's the query for the count that cause this problem.
Try the same code but don't show the count.

**Comment by matteomoretti** [comment]
It was my fault, sorry. 

Thanks for your reply.
