### ISSUE TITLE
Display filter box external from the grid.

### ISSUE THREAD

**Issue by giovkanata** [Abhoryo/APYDataGridBundle#691]
I can't find in the docs how to set all filter box external from the grid (as shown in your [screenshot](https://github.com/Abhoryo/APYDataGridBundle#screenshot)).

I've missed something?

**Comment by plfort** [comment]
Hello,
https://github.com/Abhoryo/APYDataGridBundle/blob/master/Resources/doc/template/render_external_filters.md

**Comment by giovkanata** [comment]
Thank You very much!
But how did I not see it?
I think I will have to take a vacation ... I'm a bit tired:-).
