### ISSUE TITLE
prefiltering grid

### ISSUE THREAD

**Issue by matthbull** [Abhoryo/APYDataGridBundle#695]
I understand that you can effectively pre-filter a grid using setDefaultFilters, but as I understand it this only works on query based source data.

is there a way to prefilter the grid using the filters specified by a user in the client.  For instance, a user clicks a link in a grid, which takes them to a new prefiltered grid based on the type/content of the link they clicked on.  Ive looked through session and cookie data and cant find where the grid stores its state.

**Comment by Abhoryo** [comment]
Grids are indead stored in session with its id (grid_<id>) or hash as identifier.
You can pass filters in the query string directly.
For the grid with the id `my_grid` and the column `column_1` and another column `column_2`

http://url.to.my.grid/?grid_my_grid[column_1]=value_1&grid_my_grid[column_2]=value_2

**Comment by matthbull** [comment]
awesome, many thanks. I couldnt find query string usage in your documentation
