### ISSUE TITLE
Adding hidden field in the grid

### ISSUE THREAD

**Issue by FredDut** [Abhoryo/APYDataGridBundle#697]
Hello,
I have a search box to search in several attributes (of several entities in the future). 
I render the results with datagrid.
The problem is when I click on the following pages, the searched text is lost (as it's post data).
How can add an hidden field to the datagrid, with the searched text?
Or may be it's not the good way?

Thanks

**Comment by Abhoryo** [comment]
Look how the external search works and do the same.

**Comment by FredDut** [comment]
Hello,
I've tried several ways. The hidden field in the grid is not possible because of the redirect response (we lost post data). As I wanted to be able to have several search at the same time (in different windows or tabs),  I use session variables and a route generated with the slug of the searched text. I use setdata to filter and grid manager to render all the grids.
Best regards
