### ISSUE TITLE
ClassNotFoundException: Attempted to load class "Column" from namespace "APY\DataGridBundle\Grid".

### ISSUE THREAD

**Issue by userfriendly** [Abhoryo/APYDataGridBundle#714]
Hi there

I was wondering if you could help me with a weird issue I'm having after upgrading to Symfony 2.7, I'm getting this `ClassNotFoundException` here:

    Attempted to load class "Column" from namespace "APY\DataGridBundle\Grid".
    Did you forget a "use" statement for e.g. "PHPExcel_Worksheet_AutoFilter_Column", "Doctrine\ORM\Mapping\Column", "Doctrine\DBAL\Schema\Column", "APY\DataGridBundle\Grid\Column\Column" or "APY\DataGridBundle\Grid\Mapping\Column"

The strange thing is that the class it's complaining about, `APY\DataGridBundle\Grid\Column`, isn't used in my code at all, I'm using for example `APY\DataGridBundle\Grid\Column\ActionColumn` or `APY\DataGridBundle\Grid\Column\TextColumn` etc., but not `APY\DataGridBundle\Grid\Column`. So I'm a bit puzzled where this is coming from. I'm hoping it may be something silly and easily resolved, i.e. something stupid I'm doing. Any ideas? :)

Thanks!

**Comment by Abhoryo** [comment]
Maybe a problem with composer, check your classmap generate by composer.

**Comment by userfriendly** [comment]
The DataGridBundle related line autoload_namespaces.php looks normal/fine to me: `'APY\\DataGridBundle' => array($vendorDir . '/apy/datagrid-bundle'),`

**Comment by userfriendly** [comment]
To add something puzzling: this only happens in the dev controller, not prod - and yes, we've cleared the cache about a hundred thousand times over the past few weeks that we've been getting this.

**Comment by userfriendly** [comment]
Some more digging by a colleague revealed that it may be the case that the DataGridBundle is not working well with the symfony2.7 debugger - see the following code in debugclassloader.php:

```
if (!$parent || strncmp($ns, $parent, $len)) {
    if ($parent && isset(self::$deprecated[$parent->name]) && strncmp($ns, $parent->name, $len)) {
        trigger_error(sprintf('The %s class extends %s that is deprecated %s', $name, $parent->name, self::$deprecated[$parent->name]), E_USER_DEPRECATED);
    }

    foreach ($refl->getInterfaceNames() as $interface) {
        if (isset(self::$deprecated[$interface]) && strncmp($ns, $interface, $len) && !($parent && $parent->implementsInterface($interface))) {
            trigger_error(sprintf('The %s %s %s that is deprecated %s', $name, $refl->isInterface() ? 'interface extends' : 'class implements', $interface, self::$deprecated[$interface]), E_USER_DEPRECATED);
        }
    }
}
```

This appears to be meant to load the parent class (hence loading something we're not calling), but doesn't seem to be compatible with the DataGridBundle. If that's commented out, the exception reported above is gone.

However, that's something in one of the Symfony bundles, and I'd rather not fork one of them. Is this something they screwed up, or would you think that the issue is with this bundle instead?

**Comment by userfriendly** [comment]
Submitted a PR to the Symfony devs: https://github.com/symfony/symfony/pull/14422

Still puzzled why it would break, mind.

**Comment by Abhoryo** [comment]
Never tested with 2.7.

**Comment by userfriendly** [comment]
No worries, this was due to a bug in the debug class loader in 2.7. Fixed now.
