### ISSUE TITLE
row.getEntity() problem

### ISSUE THREAD

**Issue by constantin777** [Abhoryo/APYDataGridBundle#735]
Hello, please tell me how can I get the current entity object without associated entity objects in Twig {{ row.getEntity }},,i don't want get all relation for current entity

**Comment by b-durand** [comment]
Doctrine defines the entity and association mappings (lazy or eager load). The problem is not to look towards this bundle imho.

To be more specific in your needs if you want a good answer. Why do you need access entity from the view instead of using the manipulateRow method?

**Comment by constantin777** [comment]
because manipulate Row i do not have access to function ,,for example  {{ row.getEntity().canDeleted() }} in twig,,, And I do not want to get all the related entity when i call row.getEntity() methods I have a problem page optimization, pages download very slow

**Comment by constantin777** [comment]
how to can i set Entity object in my grid field ,so I got access to it in twig without a method  row.getEntity() ?
