### ISSUE TITLE
time-ago-in-words

### ISSUE THREAD

**Issue by grekpg** [Abhoryo/APYDataGridBundle#763]
How i can setup this twig filter to date render ? https://github.com/salavert/time-ago-in-words

**Comment by giovkanata** [comment]
You can extend the APY template to override the block where you want to add the filter or you can also decouple the code from the filter (and obviously reuse it also in the twig filter) to create a Symfony Service and use it during the construction of the grid like in this example (function and service names are only an example):
```
$grid = $this->get('grid');

$entity = new \APY\DataGridBundle\Grid\Source\Entity('YourProject\YourBundle\EntityFolder\YourEntity');

$entity->manipulateRow(
			function ($row) {
				$timeAgoConverter = $this->controller->get('your_time_ago_service');
				$convertedData = $timeAgoConverter->convertDataInWords($row->getField('yourDataFieldName'));
				$row->setField('yourDataFieldName', $convertedData);

				return $row;
			}
		);

$grid->setSource($entity);
```

**Comment by grekpg** [comment]
Thanks fot this example. Is possible to setup twig filter in entity annotation?

**Comment by giovkanata** [comment]
Not using the filter directly. You have to decouple the code in a service and use it inside a [custom validator constraint](http://symfony.com/doc/current/cookbook/validation/custom_constraint.html)

**Comment by giovkanata** [comment]
Not using the filter directly. To use it using annotations you have to decouple the code in a [service](http://symfony.com/doc/current/book/service_container.html) and use it inside a custom annotation (search on StackOverflow)
