### ISSUE TITLE
Sort a simple integer column

### ISSUE THREAD

**Issue by ymc-sise** [Abhoryo/APYDataGridBundle#764]
Could anyone give me a hint how I do a sorting on a simple integer column? I would like to have a select dropdown where I can choose between ascending or descending order.

Thank you

**Comment by tomcyr** [comment]
@ymc-sise why select??
You can do that by clicking on the header of your column (one click sorting ASC, one more click sorting DESC)

**Comment by ymc-sise** [comment]
Oh I completely missed that :) Thank you!
