### ISSUE TITLE
No metadata information has been found for

### ISSUE THREAD

**Issue by aleperin** [Abhoryo/APYDataGridBundle#768]
Hello !, install the Bundle and perform a basic configuration and issues the following error:

**No metadata information has been found for ASPHU\BackEndBundle\Entity\Perfiles (group : default)**

![capturaapy](https://cloud.githubusercontent.com/assets/7596760/11094151/deaf771e-886c-11e5-9b69-810f8db7b0a9.JPG)

With the following code:

```php
    public function bylGridAction()
    {
        // Creates simple grid based on your entity (ORM)
        $source = new Entity('ASPHUBackEndBundle:Perfiles');
        
        // Get a grid instance
        $grid = $this->get('grid');

        // Attach the source to the grid
        $grid->setSource($source);

        // Configuration of the grid

        // Manage the grid redirection, exports and the response of the controller
        return $grid->getGridResponse('ASPHUTestBundle:Byl:grid.html.twig');
    }
```

I expect a prompt response and I can fix it!

Thanks and regards!

**Comment by tomcyr** [comment]
@aleperin You must add grid annotations in your Entity class:

```php
namespace ASPHU\BackEndBundle\Entity\Perfiles;

use APY\DataGridBundle\Grid\Mapping as GRID;

/**
 * @ORM\Entity
 * @GRID\Source(columns="id, yourColumn1, yourColumn2, ...")
 */
class Perfiles
{
```

**Comment by aleperin** [comment]
Thanks Tom !, I run correctly !!!!

Another question, you can display an image in a cell?

![image](https://cloud.githubusercontent.com/assets/7596760/11118350/f820cb90-891f-11e5-889b-b369027070b2.png)

Thanks and regards!

**Comment by tomcyr** [comment]
@aleperin Yes, you can. Read the docs:
https://github.com/Abhoryo/APYDataGridBundle/blob/master/Resources/doc/columns_configuration/types/create_column.md
:)

**Comment by aleperin** [comment]
Hi thanks!
I have a query ...
I have the following error:
![image](https://cloud.githubusercontent.com/assets/7596760/11153755/c3d982fa-8a19-11e5-8ce5-c742cb33860d.png)
In my entity have:
```
    /**
     * @ORM\Column(name="foto_path", type="string")
     *
     * @GRID\Column(type="video")
     */
    protected $fotoPath;    
```
New column:
C:\xampp\htdocs\asphu3v1\src\ASPHU\TestBundle\Grid\Column\VideoColumn.php
```
<?php

namespace APY\DataGridBundle\Grid\Column;

class VideoColumn extends Column
{
    protected $playerFormat;

    public function __initialize(array $params)
    {
        parent::__initialize($params);

        $this->setPlayerFormat($this->getParam('playerFormat'));

        // Disable the filter of the column
        $this->setFilterable(false);
        $this->setOrder(false);
    }

    public function setPlayerFormat($playerFormat)
    {
        $this->playerFormat = $playerFormat;

        return $this;
    }

    public function getPlayerFormat()
    {
        return $this->playerFormat;
    }

    public function getType()
    {
        return 'video';
    }
}
```
Where should I put the following code?
```
<services>
    ...
    <service id="grid.column.video" class="MyProject\MyBundle\Grid\Column\VideoColumn" public="false">
        <tag name="grid.column.extension" />
    </service>
    ...
</services>
```
Thank you very much and best regards!

**Comment by tomcyr** [comment]
@aleperin If You are using xml configuration files paste this into app/config/services.xml

**Comment by aleperin** [comment]
Hello, my service is yml format .... Can you help me get through XML format yml ....
Thank you!

**Comment by tomcyr** [comment]
It's quite easy:
```yml
services:
    grid.column.video:
        class: MyProject\MyBundle\Grid\Column\VideoColumn
        public: false
        tags:
          - {name: grid.column.extension}
```

**Comment by aleperin** [comment]
Thank you for your patience...
Excuse me ... but it gives the same error ...
![image](https://cloud.githubusercontent.com/assets/7596760/11183646/d271a448-8c51-11e5-854b-31ca9662d924.png)


![image](https://cloud.githubusercontent.com/assets/7596760/11183635/b65dfaae-8c51-11e5-8da7-e3bde0308854.png)

![image](https://cloud.githubusercontent.com/assets/7596760/11183668/f05d8346-8c51-11e5-8f1b-9f5518902623.png)

Thanks if you can help me ....

**Comment by tomcyr** [comment]
@aleperin added you display block for this column in your grid template ??
```twig
{% block grid_column_type_video_cell %}
    {# Show your player with the file path store in the variable {{ value }} #}
{% endblock grid_column_type_video_cell %}
```

**Comment by aleperin** [comment]
Hello !, the could not get to that point, because the error is on the line 74 and gives the error message ....
![image](https://cloud.githubusercontent.com/assets/7596760/11215624/02470e9a-8d26-11e5-9bf7-146bc7329f9d.png)

**Comment by Charlie-Lucas** [comment]
Maybe clear your cache as recommended.

**Comment by aleperin** [comment]
Hello !, I found the error, in VideoColumn.php:

![image](https://cloud.githubusercontent.com/assets/7596760/11247168/ab292588-8df9-11e5-998b-57685f521d2d.png)

Now, when I arm the view grid3.html.twig:
``` 
{% extends 'APYDataGridBundle::blocks.html.twig' %}
{% block grid_column_type_video_cell %}
    {# Show your player with the file path store in the variable {{ value }} #}
    <img src="{{ value }}" alt="" />
{% endblock grid_column_type_video_cell %}
```
Issues the following error:

![image](https://cloud.githubusercontent.com/assets/7596760/11247347/7c18761c-8dfa-11e5-8e18-077701cf4585.png)

That will be bad?

Thanks and regards!

**Comment by Charlie-Lucas** [comment]
Have you set your custom theme in [configuration](https://github.com/Abhoryo/APYDataGridBundle/blob/master/Resources/doc/template/overriding_internal_blocks.md#external-template)?

**Comment by aleperin** [comment]
Hello Charlie !, help me with the lines I write for my grid table on a twig?

Thank you!

**Comment by Charlie-Lucas** [comment]
Exemple of users avatar display column, i use vlabs for files:
User.php:
```
    /**
     * @var VlabsFile
     *
     * @ORM\ManyToOne(targetEntity="Avatar", cascade={"persist"})
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="avatar_id", referencedColumnName="id")
     * })
     *
     * @Vlabs\Media(identifier="user_avatar", upload_dir="uploads/user-avatar")
     * @Assert\Valid()
     * @VIC\BusinessProperty("imageable")
     * @GRID\Column(type="avatar")
     *
     */
    protected $avatar;
```
my Avatar Column class:
```
<?php

namespace Wweeddoo\Admin\AppBundle\Grid\Column;

class AvatarColumn extends \APY\DataGridBundle\Grid\Column\Column
{

    public function __initialize(array $params)
    {
        parent::__initialize($params);
        $this->setFilterable(false);
        $this->setOrder(false);
    }
    public function getType()
    {
        return 'avatar';
    }
}
```
my services.yml
```
    grid.column.avatar:
        class: Wweeddoo\Admin\AppBundle\Grid\Column\AvatarColumn
        public: false
        tags:
          - {name: grid.column.extension}
```
and then i rewrite blocks.html.twig  on app/Ressources : 
```
{% block grid_column_avatar_cell %}
    <img src="{{ value|default('/bundles/noosterfronttemplate/images/default-avatar.png')|imagine_filter('login_picture_mini') }}"/>
{% endblock grid_column_avatar_cell %}
```

**Comment by aleperin** [comment]
Hello works! with the following code:
```
  <body>
    {% block content %}
        {{ grid(grid, _self) }}
    {% endblock content %}
    {% block grid_column_video_cell %}
        <p>Imagen:<img alt='{{ value }}' src='{{ value }}' width="100px"/></p>
    {% endblock grid_column_video_cell %}
  </body>
```

But I add this object at the end ....

![image](https://cloud.githubusercontent.com/assets/7596760/11249188/39d290da-8e04-11e5-8d41-fefd3351be6a.png)


Because it will be?

**Comment by Charlie-Lucas** [comment]
look twig documentation if you just write a block like this you it will appear extends another template with for example:
layout.html.twig
```
<html>
    <head></head>
    <body>{% block content %}{% endblock %}
</html>
```
grid.html.twig
```
{% extends 'layout.html.twig' %}
{% block content %}
        {{ grid(grid, _self) }}
    {% endblock content %}
    {% block grid_column_video_cell %}
        <p>Imagen:<img alt='{{ value }}' src='{{ value }}' width="100px"/></p>
    {% endblock grid_column_video_cell %}
```

**Comment by aleperin** [comment]
I did as you indicated, but the object is still displayed at the end of the table, see picture:

![image](https://cloud.githubusercontent.com/assets/7596760/11251729/5c591b44-8e11-11e5-9b8c-498fc44dc52b.png)

Thanks!

**Comment by Charlie-Lucas** [comment]
If you place pour block on block.HTML.twig it will work without appear

**Comment by Charlie-Lucas** [comment]
@aleperin can you close the issue?

**Comment by aleperin** [comment]
Yes!
Greetings!

**Comment by mikemirten** [comment]
> @aleperin You must add grid annotations in your Entity class

The docs says:

_The Source annotation for a class allows to configure the grid.
It's **optional** if you have declare Column annotation for your properties._

So it is still a bug. And actually the bug is quite serious. I have an auto-generated entities in my project and the columns/properties definition is a traits which used by an entity classes which contains business logic. It means i cannot define the GRID list by the "Source" annotation, but according to the docs i could do it through the "Column" annotations.

**Comment by jstnthms** [comment]
Is there really no way to use the GRID without annotations? This doesn't make sense. What if I want to create a GRID for an entity from a 3rd-party bundle? I can't add annotations to the 3rd-party code, and I'm sure as hell not going to start copy/pasting properties from that 3rd-party entity just so I can add annotations.
