### ISSUE TITLE
Ajax search breaks Select2 script and CSS

### ISSUE THREAD

**Issue by MlleDelphine** [Abhoryo/APYDataGridBundle#770]
Hi there !

I'm calling my datagrid like that

`  {{  render(controller('BackendBundle:Contact:showContactLogs', {"id": contact.id})) }}`

And I'm using custom jquery template (copy of block_js.jquery.html.twig) which extends a custom view which itself extends blocks.html
` {% extends 'APYDataGridBundle::blocks.html.twig' %}` 

Actually, when I launch a search, results found are good ones but CSS is broken (table is larger than before search) and select input do not have autocomplete (Select2.js) anymore.
CSS is broken because select2 div is missing after and I have a rule on it.

Moreover, pagination does not work but pagination elements are displayed.

PS : I have an JS error everytime (even with orignal jQuery template)

`ReferenceError: $ is not defined
       $(function () {`

Which corresponds to line 53 in my custom jQuery template (same as APY block_js.jquery.html.twig template)

Someone else has been in trouble with using `  {{  render(controller( ` and Select2 ?

**Comment by plfort** [comment]
It seems Jquery is not loaded

On Tue, Nov 17, 2015 at 4:50 PM, MlleDelphine <notifications@github.com>
wrote:

> Hi there !
>
> I'm calling my datagrid like that
>
> {{ render(controller('BackendBundle:Contact:showContactLogs', {"id":
> contact.id})) }}
>
> And I'm using custom jquery template (copy of block_js.jquery.html.twig)
> which extends a custom view which itself extends blocks.html
> {% extends 'APYDataGridBundle::blocks.html.twig' %}
>
> Actually, when I launch a search, results found are good ones but CSS is
> broken (table is larger than before search) and select input do not have
> autocomplete (Select2.js) anymore.
>
> Moreover, pagination does not work but pagination elements are displayed.
>
> PS : I have an JS error everytime (even with orignal jQuery template)
>
> ReferenceError: $ is not defined
> $(function () {
>
> Which corresponds to line 53 in my custom jQuery template (same as APY
> block_js.jquery.html.twig template)
>
> Someone else has been in trouble with using {{ render(controller( ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Abhoryo/APYDataGridBundle/issues/770>.
>



-- 
FORT Pierre-Louis

**Comment by MlleDelphine** [comment]
Ok, so, where sould I load it ? It's loaded in my layout template.

And I know that an ajax refresh can breaks Select2 effect until we apply select2 script to a level highter. But, I do not know where select2 script is launched for "contains, equals, between,..." filters.

**Comment by MlleDelphine** [comment]
Ok so I solved my select2 issue by adding after ajax call in `{% block grid_scripts_goto %}` in my extended jquery template. :

`$(document).find('select').select2();`

But I can't solved the jQuery error and I have to launch twice my search.. First try does not work. Same cause ?
