### ISSUE TITLE
Custom query and custom column

### ISSUE THREAD

**Issue by mmaximo33** [Abhoryo/APYDataGridBundle#777]
Hi, I have my grid when it contains the Custom Column by an entity, now you need to make a query about this but does not show me the CustomColumn (fotoPath).

**Work CustomColumn**
![image](https://cloud.githubusercontent.com/assets/12983255/11449950/a3c11ad2-9568-11e5-8248-7ddf3081547f.png)

```php
<?php
use APY\DataGridBundle\Grid\Source\Entity;

$source = new Entity('ASPHUAppBundle:Auditorias');

$grid = $this->get('grid');

$grid->setSource($source);

return $grid->getGridResponse('grid.html.twig');

```

**Not nork CustomColumn**
![image](https://cloud.githubusercontent.com/assets/12983255/11449955/dc954c0c-9568-11e5-9aee-7cbf707c3005.png)

```php
<?php
use APY\DataGridBundle\Grid\Source\Vector;

$query = $this->getDoctrine()->getManager()->createQuery
("
    SELECT
        a.id,
        a.inspeccion
        a.fotoPath,
    FROM 
        ASPHUAppBundle:Auditorias a
    WHERE 
        a.tarea = '" . $tipo . "'"
);

$data = $query->getArrayResult();

$source= new Vector($data);

$grid = $this->get('grid');

$grid->setSource($source);

return $grid->getGridResponse('grid.html.twig');

```

Thank you!!!

**Comment by qferr** [comment]
Hello,

You can manipulate the query with a a callback method or custom QueryBuilder. Look [this](https://github.com/Abhoryo/APYDataGridBundle/blob/master/Resources/doc/grid_configuration/manipulate_query.md).

**Comment by mmaximo33** [comment]
Excelent, thank you!!!
